#配置默认启动端口
server:
  port: 9090

#  数据库配置
spring:
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-file-size: 20MB #设置单个文件最大长度
      max-request-size: 100MB #最大请求文件的大小
  main:
    allow-circular-references: true
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/2024_bookstore?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: 111111

# mybatis相关配置
mybatis:
  #  包所在路径
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.springboot.entity
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql



